repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: markdown-link-check
        name: markdown_lint
        description: Run markdown lint on markdown files