site_name: Ways of Working
#site_url: https://wow.nevinia.co.uk
site_description: Platform Engineering - Best practices, standards, policies & procedures
site_author: Declan Griffith-Barwell

theme:
  name: material
  font:
    text: Roboto
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
      primary: pink
    # Palette toggle for light mode
    - media: "(prefers-colour-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to system preference
      primary: pink
    # Palette toggle for dark mode
    - media: "(prefers-colour-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: pink
  logo: img/dtp-crop-circle.png
  favicon: img/favicon-16x16.png
  features:
    - navigation.instant
    - navigation.indexes

plugins:
  - search

markdown_extensions:
  - tables
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.details